#!/bin/bash

gcc keygen.c -o keygen

gcc otp_enc_d.c serverfunctions.c -o otp_enc_d -g

gcc otp_dec_d.c serverfunctions.c -o otp_dec_d -g

gcc otp_enc.c clientfunctions.c -o otp_enc -g

gcc otp_dec.c clientfunctions.c -o otp_dec -g
